CUDA_VISIBLE_DEVICES=0,1 python ttavlm/main.py \
--exp_name cliptta_imagenet \
--adaptation cliptta_old \
--distributed \
--dataset imagenet \
--shift_type original \
--steps 10 \
--seeds 42 \
--lr 1e-4 \
--beta_tta 1.0 \
--beta_reg 1.0 \
--id_score_type max_prob \
--use_softmax_entropy \
--use_memory \
--num_shots 16 \
--sample_size 64 \
--batch_size 256 \
--closed_set \

CUDA_VISIBLE_DEVICES=0,1 python ttavlm/main.py \
--exp_name cliptta_imagenetc \
--adaptation cliptta_old \
--distributed \
--dataset imagenetc \
--shift_type all \
--steps 10 \
--seeds 42 \
--lr 1e-4 \
--beta_tta 1.0 \
--beta_reg 1.0 \
--id_score_type max_prob \
--use_softmax_entropy \
--use_memory \
--num_shots 16 \
--sample_size 64 \
--batch_size 256 \
--closed_set \
